### ISSUE TITLE
ILIAS and Moodle import/export issue 

### ISSUE THREAD

**Issue by malthesporring** [surlabs/STACK#68]
I may have found an import/export issue between ILIAS and Moodle version of STACK. The attached question comes from ILIAS, but when imported into the Moodle version of STACK:
- question variables are all given in one-line, and if semicolons were not used at the end of each line, the question does not work in STACK. Can we make the ILIAS export enter semicolons as needed?
-  There is no validation box. Can you confirm this question works in ILIAS?

Can you reproduce this issue?

[stack_question_90604.zip](https://github.com/ilifau/assStackQuestion/files/3504994/stack_question_90604.zip)

**Comment by jcopado** [comment]
Hello Malthe,

I reproduced this issue in our Moodle installation (Moodle 3.4), the question variables are properly imported in moodle, even if no semicolons were used, the problem comes because there is no validation placeholder, so the question cannot be validated in Moodle. In ILIAS this questions works properly. Definitely there is a conflict between in Moodle and ILIAS behaviour,so, we will try to solve it as soon as possible, I will inform you here when we find the best solution for this issue,

Thank you for the report!
